Repository bounswe/bounswe2023group9, pull requests merged in 2023-05, with the labels that each got.

#101 Initial Commit
  practice_app/manage.py
  practice_app/practice_app/__init__.py
  practice_app/practice_app/asgi.py
  practice_app/practice_app/settings.py
  practice_app/practice_app/urls.py
  practice_app/practice_app/wsgi.py
Labels: priority: high, type: repository

#113 SerpApi GET Method Implementation
  .github/workflows/django.yml
  practice_app/api/__init__.py
  practice_app/api/api_keys.py
  practice_app/api/tests.py
  practice_app/api/urls.py
  practice_app/api/views.py
  practice_app/practice_app/settings.py
  practice_app/requirements.txt
Labels: status: needs-review, size: medium, difficulty: moderate, type: implementation

#118 ERIC API GET Method Implementation
  practice_app/api/tests.py
  practice_app/api/urls.py
  practice_app/api/views.py
  practice_app/practice_app/settings.py
Labels: status: in-review, size: medium, difficulty: moderate, type: implementation

#122 doaj_api GET method
  practice_app/api/tests.py
  practice_app/api/urls.py
  practice_app/api/views.py
  practice_app/practice_app/settings.py
Labels: status: in-review, size: medium, difficulty: moderate, type: implementation

#129 Adding Third Party API keys to the Test Environment
  .github/workflows/django.yml
  practice_app/practice_app/settings.py
Labels: type: repository, status: needs-review, size: small, difficulty: easy

#128 Update models.py and admin.py
  practice_app/api/admin.py
  practice_app/api/models.py
Labels: priority: medium, status: in-review, size: medium, type: implementation

#125 semantic scholar api and tests
  practice_app/api/tests.py
  practice_app/api/urls.py
  practice_app/api/views.py
Labels: priority: medium, status: in-review, size: medium, difficulty: moderate, type: implementation

#133 Coreacuk api get method implementation
  practice_app/api/api_keys.py
  practice_app/api/tests.py
  practice_app/api/urls.py
  practice_app/api/views.py
  practice_app/requirements.txt
Labels: priority: high, type: enhancement, status: needs-review, size: large, difficulty: moderate

#132 ORCID API GET Method and Registration/Login POST Methods
  practice_app/api/tests.py
  practice_app/api/urls.py
  practice_app/api/views.py
Labels: priority: high, status: in-review, size: medium, difficulty: moderate, type: implementation

#145 Correcting GET Methods
  practice_app/api/models.py
  practice_app/api/tests.py
  practice_app/api/views.py
Labels: bug, status: needs-review, size: small, difficulty: easy

#154 Post Papers POST API Method
  .github/workflows/django.yml
  practice_app/api/tests.py
  practice_app/api/urls.py
  practice_app/api/views.py
Labels: priority: critical, status: needs-review, size: medium, difficulty: moderate, type: implementation

#153 POST Method to Send Follow Request
  practice_app/api/tests.py
  practice_app/api/urls.py
  practice_app/api/views.py
Labels: priority: high, status: in-review, size: medium, difficulty: moderate

#158 updating API URLs to use hyphens
  practice_app/api/tests.py
  practice_app/api/urls.py
Labels: priority: low, type: enhancement, status: needs-review, size: small, difficulty: easy

#148 Front end sign in page
  practice_app/front_end/__init__.py
  practice_app/front_end/admin.py
  practice_app/front_end/apps.py
  practice_app/front_end/models.py
  practice_app/front_end/templates/base.html
  practice_app/front_end/templates/pages/follow_requests.html
  practice_app/front_end/templates/pages/following_lists.html
  practice_app/front_end/templates/pages/list_content.html
  practice_app/front_end/templates/pages/my_lists.html
  practice_app/front_end/templates/pages/paper_content.html
  practice_app/front_end/templates/pages/profile_page.html
  practice_app/front_end/templates/pages/search_paper.html
  practice_app/front_end/templates/pages/search_user.html
  practice_app/front_end/templates/pages/sign_in.html
  practice_app/front_end/tests.py
  practice_app/front_end/views.py
  practice_app/practice_app/settings.py
  practice_app/practice_app/urls.py
Labels: priority: critical, status: in-review, size: large, difficulty: challenging, type: implementation

#155 POST method to save paper lists
  practice_app/api/tests.py
  practice_app/api/urls.py
  practice_app/api/views.py
Labels: priority: high, status: in-review, size: medium, difficulty: moderate, type: implementation

#171 Create paper list post method
  practice_app/api/tests.py
  practice_app/api/urls.py
  practice_app/api/views.py
Labels: priority: critical, status: needs-review, difficulty: moderate, type: implementation

#173 GET Method for NASA STI OpenAPI
  practice_app/api/tests.py
  practice_app/api/urls.py
  practice_app/api/views.py
Labels: priority: medium, priority: high, status: needs-review, size: medium, difficulty: moderate, type: implementation

#170 Adding Followers and Following Pages and Separating Headers
  practice_app/api/views.py
  practice_app/front_end/templates/base.html
  practice_app/front_end/templates/header.html
  practice_app/front_end/templates/pages/follow_requests.html
  practice_app/front_end/templates/pages/followers.html
  practice_app/front_end/templates/pages/following.html
  practice_app/front_end/templates/pages/following_lists.html
  practice_app/front_end/templates/pages/list_content.html
  practice_app/front_end/templates/pages/my_lists.html
  practice_app/front_end/templates/pages/paper_content.html
  practice_app/front_end/templates/pages/profile_page.html
  practice_app/front_end/templates/pages/search_paper.html
  practice_app/front_end/templates/pages/search_user.html
  practice_app/front_end/templates/pages/sign_in.html
  practice_app/front_end/templates/pages/sign_up.html
  practice_app/front_end/urls.py
  practice_app/front_end/views.py
  practice_app/practice_app/urls.py
Labels: priority: critical, status: needs-review, size: small, difficulty: easy, type: implementation

#163 POST Method To Add Interests in User Profiles
  practice_app/api/tests.py
  practice_app/api/urls.py
  practice_app/api/views.py
Labels: priority: high, status: needs-review, size: medium, difficulty: moderate, type: implementation

#181 Front end implementation of the following paper lists page
  practice_app/front_end/templates/pages/following_lists.html
  practice_app/front_end/urls.py
  practice_app/front_end/views.py
Labels: status: needs-review, size: small, difficulty: easy, type: design, type: implementation

#189 Fix Author Fields of GET Methods
  practice_app/api/tests.py
  practice_app/api/views.py
Labels: bug, priority: critical, size: small, difficulty: easy

#180 Addition of add interest button
  practice_app/api/views.py
  practice_app/front_end/templates/pages/profile_page.html
  practice_app/front_end/views.py
Labels: status: needs-review, size: small, difficulty: moderate, type: design, type: implementation

#200 Addition of an empty database file into repository
  practice_app/db.sqlite3
Labels: priority: critical, status: completed, size: small, difficulty: easy, type: implementation

#213 Update views.py
  practice_app/front_end/views.py
Labels: bug, status: needs-review, size: small, difficulty: easy

#231 Handling paper content html file and view
  practice_app/front_end/templates/pages/paper_content.html
  practice_app/front_end/urls.py
  practice_app/front_end/views.py
Labels: priority: critical, status: completed, size: small, difficulty: easy, type: fix

#230 Implementation of Follow Request Page and Small Fixes on Follow Feature
  practice_app/api/views.py
  practice_app/front_end/templates/pages/follow_requests.html
  practice_app/front_end/views.py
Labels: priority: critical, status: in-review, size: medium, difficulty: moderate, type: implementation

#228 swagger ui is added
  practice_app/api/static/swagger.json
  practice_app/api/templates/swagger-ui.html
  practice_app/api/urls.py
  practice_app/practice_app/urls.py
Labels: priority: critical, type: documentation, type: implementation

#215 Dockerfile Added
  practice_app/Dockerfile
Labels: priority: critical, status: needs-review, size: medium, difficulty: easy, type: implementation

#235 fix core api date and eric authors
  practice_app/api/views.py
Labels: priority: critical, status: in-review, size: small, difficulty: easy, type: fix
